### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_electron#200]
**Describe the bug**
[platform] ERROR on export (see log)

**How To Reproduce**
1. Open Patch
2. Click on "Export"
3. [platform] ERROR

**Platform**
- MacOS Sonoma 14.3.1 (23D60)

**Logs**

```
[electron-main] 03:09:2024 17:14:16 [export_zip_standalone:114] ...export
[electron-main] 03:09:2024 17:14:16 [shared_export_service:631] ERROR exception exporter {
  line: '    at StandaloneZipExport.collectFiles (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/export/export_zip_standalone.js:118:18)',
  index: 4,
  clean: 'StandaloneZipExport.collectFiles (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/export/export_zip_standalone.js:118:18)',
  stack: 'Error\n' +
    '    at Logger._getContext (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/node_modules/cables-shared-api/utils/shared_logger.js:170:23)\n' +
    '    at Logger.error (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/utils/logger.js:32:78)\n' +
    '    at StandaloneZipExport._exportProject (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/node_modules/cables-shared-api/export/shared_export_service.js:631:23)\n' +
    '    at StandaloneZipExport.collectFiles (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/export/export_zip_standalone.js:118:18)\n' +
    '    at StandaloneZipExport.doExport (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/export/export_zip_standalone.js:45:14)\n' +
    '    at node:internal/util:431:7\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at bound doExport (node:internal/util:417:12)\n' +
    '    at ElectronApi.exportPatch (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/electron/electron_api.js:1499:34)\n' +
    '    at ElectronApi.talkerMessage (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/electron/electron_api.js:106:29)'
}
[electron-main] 03:09:2024 17:14:16 [shared_export_service:632] ERROR exc Error: ENOENT, cables.txt not found in /Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar {
  line: '    at StandaloneZipExport._exportProject (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/node_modules/cables-shared-api/export/shared_export_service.js:525:18)',
  index: 4,
  clean: 'StandaloneZipExport._exportProject (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/node_modules/cables-shared-api/export/shared_export_service.js:525:18)',
  stack: 'Error: ENOENT, cables.txt not found in /Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar\n' +
    '    at createError (node:electron/js2c/node_init:2:2002)\n' +
    '    at t.readFileSync (node:electron/js2c/node_init:2:10415)\n' +
    '    at StandaloneZipExport._addInfoFiles (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/node_modules/cables-shared-api/export/shared_export_service.js:759:28)\n' +
    '    at StandaloneZipExport._exportProject (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/node_modules/cables-shared-api/export/shared_export_service.js:525:18)\n' +
    '    at StandaloneZipExport.collectFiles (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/export/export_zip_standalone.js:118:18)\n' +
    '    at StandaloneZipExport.doExport (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/export/export_zip_standalone.js:45:14)\n' +
    '    at node:internal/util:431:7\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at bound doExport (node:internal/util:417:12)\n' +
    '    at ElectronApi.exportPatch (file:///Applications/cables-2024-09-01-nightly.app/Contents/Resources/app.asar/src/electron/electron_api.js:1499:34)'
}
```

**Comment by steam0r** [comment]
ouch, that was on me, try rc3: https://github.com/cables-gl/cables_electron/releases/tag/v0.3.0-rc3

**Comment by 60-hz** [comment]
Fixed, thanks!
