### ISSUE TITLE
Project files inaccessible from node context

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#92]
## Environment

Running 0.0.5 AppImage on NixOS 24.05-stable with KDE Wayland

## Description

I'm attempting to break out of the matrix and access a file I've put into the project directory using the [`@stdlib/fs`](https://www.npmjs.com/package/@stdlib/fs) package since the node standard library is not yet accessible:

```js
var path = op.require("path");
var readDir = op.require('@stdlib/fs/read-dir');
var readFile = op.require('@stdlib/fs/read-file');

const parentDir = path.dirname(__dirname) + '/ops';
var out = readDir.sync( parentDir );
if ( out instanceof Error ) {
    throw out;
}
console.log(out);

readFile( parentDir + '/base/test.txt', onFile );

function onFile( error, data ) {
    if (error) {
        throw error;
    }
    console.log(data);
}
```

I've tried putting a text file in both the `ops` and the `ops/base` directory, but it appears as though files that were not explicitly brought into the cables context are not made accessible:

![image](https://github.com/cables-gl/cables_electron/assets/3112763/6ea74b49-5a48-40af-81a7-a77a2e57cdd2)

```
cablesui.js:50772 reloadop  Ops.Standalone.Npmtest subpatch: 0
index.html:59 trying to load /home/zetaphor/Code/cables-patches/npm-test/node_modules/path
index.html:59 trying to load /home/zetaphor/Code/cables-patches/npm-test/node_modules/@stdlib/fs/read-dir
index.html:59 trying to load /home/zetaphor/Code/cables-patches/npm-test/node_modules/@stdlib/fs/read-file
Ops.Standalone.Npmtest?nc=109243?p=brf7Re:36 (2) ['base', 'extensions']
Ops.Standalone.Npmtest?nc=109243?p=brf7Re:42 Uncaught Error: ENOENT, dist/ops/base/test.txt not found in /home/zetaphor/.cache/appimage-run/9ff4cf436110f175bf55d2d4afaf68aa7a7a6e42c35d3049c4effa28867e0e8f/resources/app.asar
    at createError (node:electron/js2c/node_init:2:1657)
    at fsReadFileAsar (node:electron/js2c/node_init:2:8315)
    at t.readFile (node:electron/js2c/node_init:2:9449)
    at readFile (/home/zetaphor/Code/cables-patches/npm-test/node_modules/@stdlib/fs/read-file/lib/main.js:53:11)
    at new Ops.Standalone.Npmtest (Ops.Standalone.Npmtest?nc=109243?p=brf7Re:38:1)
    at Patch.createOp (cables.js:15264:50)
    at Patch.addOp (cables.js:15330:21)
    at CABLES.Patch.reloadOp (cablesui.js:50773:29)
    at cablesui.js:45531:29
    at cablesui.js:46758:28
```

## Expected Behavior:

Any files that are in the  project directory should be accessible to all parts of the patch, including its JS context via `fs` and alternatives. This behavior persists even after reloading the project.

**Comment by Zetaphor** [comment]
This is very dumb, but it's worth noting that it did work:

```js
var path = op.require("path");
var readDir = op.require('@stdlib/fs/read-dir');
var readFile = op.require('@stdlib/fs/read-file');

let parentDir = path.dirname(path.dirname(path.dirname(path.dirname(path.dirname(path.dirname(path.dirname(__dirname)))))));
parentDir = parentDir + '/Code/cables-patches/npm-test';
var out = readDir.sync( parentDir );
if ( out instanceof Error ) {
    throw out;
}
console.log( out );

readFile( parentDir + '/test.txt', 'utf8', onFile );

function onFile( error, data ) {
    if ( error ) {
        throw error;
    }
    console.log( data );
}
```

I was able to read the contents of the file stored in the patches root directory

**Comment by Zetaphor** [comment]
Absolute paths do work:

```js
var readFile = op.require('@stdlib/fs/read-file');

readFile( '/home/zetaphor/Code/cables-patches/npm-test/test.txt', 'utf8', onFile );

function onFile( error, data ) {
    if ( error ) {
        throw error;
    }
    console.log( data );
}
```

This stdlib collection also provides a handy way of walking up directories to find a target:

```js
var resolveParentPath = op.require( '@stdlib/fs/resolve-parent-path' );

resolveParentPath( '.bashrc', onPath );
function onPath( error, path ) {
    if ( error ) {
        throw error;
    }
    console.log('Path', path );
}
```

If it's too complex to expose the directory to the electron context a viable alternative would be to expose the patches directory to a global variable and then we can use the full path

**Comment by steam0r** [comment]
this probably should have some variables like op.opDir and op.patch.patchDir, and/or PatchInfo op has this as an output so it could be used the "absolute way" as seen above

**Comment by steam0r** [comment]
do this via something like `op.require("cables-standalone-op")`

**Comment by steam0r** [comment]
pathdir is ./ now in most cases, otherwise use the pathtofileurl and fileurltopath ops
