### ISSUE TITLE
Clipboard read/write is disabled in Electron

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#99]
## Environment

Running 0.0.5 AppImage on NixOS 24.05-stable with KDE Wayland

## Reproduction steps:

1. Create a new patch, add a CopyToClipboard Op and a TriggerButton
2. Trigger the CopyToClipboard Op

![image](https://github.com/cables-gl/cables_electron/assets/3112763/f7f1b856-cd5c-47d5-80f5-f08c0340cfaa)

```
code?nc=445126:101718 [Violation] Permissions policy violation: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
inCopy.onTriggered @ code?nc=445126:101718
Port._onTriggered @ cables.js:3216
Port.trigger @ cables.js:2981
inTrig.onTriggered @ code?nc=445126:106368
Port._onTriggered @ cables.js:3216
(anonymous) @ cablesui.js:6961
code?nc=445126:101718 Uncaught (in promise) DOMException: Failed to execute 'writeText' on 'Clipboard': The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
    at inCopy.onTriggered (cables:///api/ops/code?nc=445126:101718:25)
    at Port._onTriggered (file:///home/zetaphor/.cache/appimage-run/9ff4cf436110f175bf55d2d4afaf68aa7a7a6e42c35d3049c4effa28867e0e8f/resources/app.asar/dist/ui/js/cables.js:3216:52)
    at Port.trigger (file:///home/zetaphor/.cache/appimage-run/9ff4cf436110f175bf55d2d4afaf68aa7a7a6e42c35d3049c4effa28867e0e8f/resources/app.asar/dist/ui/js/cables.js:2981:31)
    at inTrig.onTriggered (cables:///api/ops/code?nc=445126:106368:13)
    at Port._onTriggered (file:///home/zetaphor/.cache/appimage-run/9ff4cf436110f175bf55d2d4afaf68aa7a7a6e42c35d3049c4effa28867e0e8f/resources/app.asar/dist/ui/js/cables.js:3216:52)
    at HTMLSpanElement.<anonymous> (file:///home/zetaphor/.cache/appimage-run/9ff4cf436110f175bf55d2d4afaf68aa7a7a6e42c35d3049c4effa28867e0e8f/resources/app.asar/dist/ui/js/cablesui.js:6961:21)
inCopy.onTriggered @ code?nc=445126:101718
Port._onTriggered @ cables.js:3216
Port.trigger @ cables.js:2981
inTrig.onTriggered @ code?nc=445126:106368
Port._onTriggered @ cables.js:3216
(anonymous) @ cablesui.js:6961
```

## Expected Behavior:

The clipboard functionality should be enabled in the Electron build.

**Comment by steam0r** [comment]
fixed in 0.0.8
